### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by Surakshaajith** [llSourcell/tensorflow_demo#4]
**I am currently using python version 3.5.2**
Z:\downloads\tensorflow_demo-master\tensorflow_demo-master>py
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**I get the following error when i run board.py and i have all the  dependencies required to run board.py**
Z:\downloads\tensorflow_demo-master\tensorflow_demo-master>py board.py
Extracting Z:/downloads/MNIST dataset\train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "board.py", line 3, in <module>
    mnist = input_data.read_data_sets(r'Z:/downloads/MNIST dataset', one_hot=True)
  File "Z:\downloads\tensorflow_demo-master\tensorflow_demo-master\input_data.py", line 150, in read_data_sets
    train_images = extract_images(local_file)
  File "Z:\downloads\tensorflow_demo-master\tensorflow_demo-master\input_data.py", line 40, in extract_images
    buf = bytestream.read(rows * cols * num_images)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python35\lib\gzip.py", line 274, in read
    return self._buffer.read(size)
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by luciano-fiandesio** [comment]
Just created a Pull request to fix this bug: https://github.com/llSourcell/tensorflow_demo/pull/5

**Comment by Surakshaajith** [comment]
This worked out for me, instead of [this](https://github.com/llSourcell/tensorflow_demo/blob/master/board.py#L3)  line, i replaced it with these lines 
```
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
```

**Comment by soumenms2015** [comment]
Hello, when I run this line , I got the below error that DataSets is not defined.
mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)
<ipython-input-10-b265738804ac> in <module>()
----> 1 mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

/notebooks/input_data.ipynb in read_data_sets(train_dir, fake_data, one_hot)

NameError: global name 'DataSets' is not defined

**Comment by Ajinkya-wan** [comment]
Same issue .

**Comment by rakis10** [comment]
Thank you for fix but now i am getting this error
```
  File "board.py", line 32, in <module>
    w_h = tf.histogram_summary("weights", W)
AttributeError: 'module' object has no attribute 'histogram_summary'
```

**Comment by SheldonGeek** [comment]
This will fix it. Add [0] to the end of this function in input_data.py
def _read32(bytestream):
    dt = numpy.dtype(numpy.uint32).newbyteorder('>')
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]

**Comment by jimut** [comment]
@SheldonGeek Thank you. Fixed this problem. Should make a PR.

**Comment by jarvis-owl** [comment]
@rakis10 
had the same problem. 

> AttributeError: module 'tensorflow' has no attribute 'histogram_summary'

These Attributes are deprecated
Found: https://github.com/tensorflow/serving/issues/270

changed [board.py](https://github.com/llSourcell/tensorflow_demo/blob/master/board.py):
l.28 and l.29 >> histogram_summary to summary.histogram
l.37 >> scalar_summary to summary.scalar
l.47 >> merge_all_summaries to summary.merge_all
l.56 >> tf.train.SummaryWriter to tf.summary.FileWriter
here i still get a warning, that passing a 'GraphDef' is deprecated and passing a 'Graph' object is proposed. [Going to fix that later]

eventually helpful: [tf API doc](https://www.tensorflow.org/api_docs/)

**Comment by aster28** [comment]
sn.jointplot(x=x,y=y,kind='hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 2219, in jointplot
    xlim=xlim, ylim=ylim)
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 1671, in __init__
    x = x[not_na]
TypeError: only integer scalar arrays can be converted to a scalar index
>>> sn.jointplot(x,y,kind='hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 2219, in jointplot
    xlim=xlim, ylim=ylim)
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 1671, in __init__
    x = x[not_na]
TypeError: only integer scalar arrays can be converted to a scalar index
>>> sn.jointplot(x,y,kind='hex')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 2219, in jointplot
    xlim=xlim, ylim=ylim)
  File "C:\Users\sonia\AppData\Local\Programs\Python\Python35\lib\site-packages\seaborn\axisgrid.py", line 1671, in __init__
    x = x[not_na]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by aster28** [comment]
Can anyone help?
